map $request_method $limit_post_only {
    POST    $binary_remote_addr;
    default "";
}

limit_req_zone $limit_post_only zone=timeline_post:10m rate=1r/m;
limit_req_status 429;

server {
    listen 80;
    server_name portfolio-mlh.duckdns.org;

    if ($host = portfolio-mlh.duckdns.org) {
        return 301 https://$host$request_uri;
    }
}

server {
    listen 443 ssl;
    server_name portfolio-mlh.duckdns.org;

    location /api/timeline_post {
        limit_req zone=timeline_post nodelay;
        proxy_pass http://myportfolio:5000;
    }

    location / {
        proxy_pass http://myportfolio:5000/;
    }

    ssl_certificate /etc/letsencrypt/live/myportfolio/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/myportfolio/privkey.pem;
    ssl_trusted_certificate /etc/letsencrypt/live/myportfolio/chain.pem;
}
